"""
backtest_older_seasons.py

F11 Session 1: can the served historical simulator score 1985-86 to 1996-97
teams honestly? Writes the evidence into reports/older_seasons_backtest.md.

1. Formula validation. For 1996-97 onward both the NBA's advanced values
   (TeamStatisticsExtended.csv) and the basic box score exist. Each
   BOX_SCORE_FORMULAS stat is computed from the box score and compared with
   the NBA's value per team-season.
2. Identity. Every 1986-97 team-season gets an era-correct, unique key
   (export_static_site_data.attach_identity raises on a duplicate).
3. Backtest. The active release never trained on 1986-97. It scores every
   1986-97 game from point-in-time (pre-game, cumulative) profiles built with
   build_matchup_training_data.attach_point_in_time_profiles, and the same
   metrics are computed on matchup_training_data.csv for its own seasons.
   The point-in-time rows are saved to data/processed/older_seasons_matchups.csv
   so src/models/test_pregame_leakage.py can check them.
4. Era drift. League-average offensive rating, pace, three-point attempt
   rate and true shooting for every season from 1986.
5. Era probe. Real games are always between two teams of the same season, so
   they cannot show cross-era bias. Two small probe models (not releases),
   trained alike on 1998-2018 point-in-time games, one on raw inputs and one
   on inputs relative to the league, are scored on real games and on every
   1987-97 versus 2022-26 neutral pairing; hist-v1 is scored on the same
   pairings.

Only the section below REPORT_MARKER is regenerated; the summary and
recommendation above it are written by hand and kept.

Run from repo root (after build_matchup_training_data.py):
    python scripts/backtest_older_seasons.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

REPO_ROOT = Path(__file__).resolve().parent.parent
for _p in (REPO_ROOT, REPO_ROOT / "backend" / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from build_matchup_training_data import attach_point_in_time_profiles, load_games
from build_team_season_profiles_extended import (
    BASIC_STATS_PATH,
    BOX_SCORE_FORMULAS,
    EXTENDED_STATS_START,
    GAME_TYPE_PLAYOFF,
    GAME_TYPE_REGULAR,
    MEAN_STATS,
    MODERN_ERA_START,
    OLDER_ERA_START,
    POSSESSION_SCALE,
    STATS_PATH,
    UNMATCHED_FORMULA_COLS,
    _read_team_games,
    build_season_profiles,
    compute_box_score_advanced,
    estimate_possessions,
    load_allowed_team_ids,
    load_team_games,
    with_opponent_box,
)
from scripts.export_static_site_data import attach_identity
from src.models.release import load_active_release

MATCHUP_PATH = REPO_ROOT / "data" / "processed" / "matchup_training_data.csv"
OLDER_PATH   = REPO_ROOT / "data" / "processed" / "older_seasons_matchups.csv"
REPORT_PATH  = REPO_ROOT / "reports" / "older_seasons_backtest.md"

REPORT_MARKER = "<!-- Everything below is generated by scripts/backtest_older_seasons.py -->"

FIRST_SEASON      = OLDER_ERA_START + 1    # 1986
LAST_OLDER_SEASON = MODERN_ERA_START       # 1997
SCALE_FIT_LAST    = 2010                   # POSSESSION_SCALE fit on seasons <= this

# A formula is usable when its mean team-season error is under this share of
# the gap between an average (50th percentile) and a good (80th) team-season.
USABLE_ERROR_SHARE = 0.25

PERIODS = [
    ("1986-1997 (never trained on)",          FIRST_SEASON, LAST_OLDER_SEASON),
    ("1998-2018 (training seasons)",          1998, 2018),
    ("2019-2021 (validation seasons)",        2019, 2021),
    ("2022-2026 (test seasons)",              2022, 2026),
]

CALIBRATION_BINS = np.linspace(0, 1, 11)

# Era probe: inputs, all point-in-time regular-season profile stats that exist
# for every season (rebound percentages are left out: UNMATCHED_FORMULA_COLS).
PROBE_STATS = [
    "regular_win_pct", "regular_net_rating", "regular_offensive_rating", "regular_defensive_rating",
    "regular_pace", "regular_true_shooting_percentage", "regular_effective_field_goal_percentage",
    "regular_opponent_effective_field_goal_percentage", "regular_team_turnover_percentage",
    "regular_opponent_turnover_percentage", "regular_three_pt_pct", "regular_ft_pct",
]
PROBE_TRAIN       = (1998, 2018)
PROBE_OLDER_PAIRS = (FIRST_SEASON + 1, LAST_OLDER_SEASON)   # 1986 has no previous season
PROBE_MODERN_PAIRS = (2022, 2026)

# Per-game raw values -> league-average era table
DRIFT_STATS = [
    ("Off. rating", "offensiveRating", 1),
    ("Pace",        "pace",            1),
    ("3PA rate",    "three_rate",      3),
    ("TS%",         "trueShootingPercentage", 3),
]


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------

def fmt(x, digits=3) -> str:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "n/a"
    return f"{x:,.{digits}f}"


def md_table(headers: list, rows: list) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 1. Formula validation
# ---------------------------------------------------------------------------

def stat_name_for(source_col: str) -> str:
    for name, (col, _digits) in MEAN_STATS.items():
        if col == source_col:
            return name
    raise ValueError("No MEAN_STATS entry reads " + source_col)


def validate_formulas(allowed_ids: set) -> tuple[str, dict]:
    """Compare every formula with the NBA's value per team-season, 1996-97 on."""
    nba = _read_team_games(STATS_PATH)
    nba = nba[(nba["season"] > EXTENDED_STATS_START) & nba["teamId"].isin(allowed_ids)]
    nba = nba[nba["gameType"].isin([GAME_TYPE_REGULAR, GAME_TYPE_PLAYOFF])]
    est = compute_box_score_advanced(nba)

    # Possession scale: fit on early seasons, check on later ones
    g = with_opponent_box(nba)
    raw = estimate_possessions(g, scale=1.0)
    fit = g["season"] <= SCALE_FIT_LAST
    fitted_scale = float(g.loc[fit, "possessions"].sum() / raw[fit].sum())
    poss_rows = []
    for label, scale in (("Standard formula (scale 1.0)", 1.0),
                         ("Fitted on " + str(EXTENDED_STATS_START + 1) + "-" + str(SCALE_FIT_LAST)
                          + " (scale " + fmt(fitted_scale, 4) + ")", fitted_scale),
                         ("As used (POSSESSION_SCALE " + str(POSSESSION_SCALE) + ")", POSSESSION_SCALE)):
        err = scale * raw - g["possessions"]
        held = ~fit
        poss_rows.append([label, fmt(err[fit].mean(), 2), fmt(err[held].mean(), 2),
                          fmt(err[held].abs().mean(), 2)])

    keys = ["teamId", "season", "gameType"]
    verdicts = {}
    rows = []
    for col in BOX_SCORE_FORMULAS:
        a = nba.groupby(keys)[col].mean()
        b = est.groupby(keys)[col].mean()
        for game_type in (GAME_TYPE_REGULAR, GAME_TYPE_PLAYOFF):
            if game_type == GAME_TYPE_PLAYOFF and col not in ("offensiveRating", "defensiveRating", "netRating", "trueShootingPercentage"):
                continue
            aa = a.xs(game_type, level="gameType")
            bb = b.xs(game_type, level="gameType")
            diff = (bb - aa).dropna()
            gap  = aa.quantile(0.8) - aa.quantile(0.5)
            if col in ("defensiveRating", "opponentEffectiveFieldGoalPercentage", "teamTurnoverPercentage",
                       "opponentFreeThrowAttemptRate", "opponentOffensiveReboundPercentage"):
                gap = aa.quantile(0.5) - aa.quantile(0.2)   # lower is better
            mae  = diff.abs().mean()
            share = mae / abs(gap) if gap else np.nan
            usable = bool(share < USABLE_ERROR_SHARE)
            prefix = "regular" if game_type == GAME_TYPE_REGULAR else "playoff"
            verdicts[col] = verdicts.get(col, True) and usable
            rows.append([
                prefix + "_" + stat_name_for(col),
                str(len(diff)),
                fmt(aa.mean(), 3), fmt(diff.mean(), 3), fmt(mae, 3), fmt(diff.abs().max(), 3),
                fmt(gap, 3), fmt(share * 100, 0) + "%", "yes" if usable else "**no**",
            ])

    text = "\n\n".join([
        "Possessions per team-game against the NBA's count (error = estimate - NBA). "
        "Fit period: seasons " + str(EXTENDED_STATS_START + 1) + "-" + str(SCALE_FIT_LAST)
        + "; held-out: " + str(SCALE_FIT_LAST + 1) + " on.",
        md_table(["Possession estimate", "Bias, fit seasons", "Bias, held-out", "Mean abs. error, held-out"], poss_rows),
        "Per team-season averages, " + str(EXTENDED_STATS_START + 1) + "-2026, formula minus NBA value. "
        "\"Avg-to-good gap\" is the distance between the 50th and 80th percentile team-season "
        "(20th and 50th where lower is better). A stat is usable when its mean absolute error "
        "is under " + str(int(USABLE_ERROR_SHARE * 100)) + "% of that gap. Stats marked **no** "
        "are left blank for seasons before 1996-97 (`UNMATCHED_FORMULA_COLS`).",
        md_table(["Profile stat", "Team-seasons", "NBA mean", "Bias", "Mean abs. error", "Max abs. error",
                  "Avg-to-good gap", "Error / gap", "Usable"], rows),
    ])
    failed = sorted(c for c, ok in verdicts.items() if not ok)
    if failed != sorted(UNMATCHED_FORMULA_COLS):
        raise ValueError("Formula verdicts changed: failing " + str(failed) + " but UNMATCHED_FORMULA_COLS is "
                         + str(sorted(UNMATCHED_FORMULA_COLS)) + ". Update the profile builder.")
    return text, verdicts


# ---------------------------------------------------------------------------
# 2. Identity
# ---------------------------------------------------------------------------

def identity_section(older_profiles: pd.DataFrame) -> str:
    ident = attach_identity(older_profiles)   # raises ValueError on a duplicate key
    old = ident[ident["season"] <= LAST_OLDER_SEASON]
    by_name = (old.groupby(["era_city", "era_name"])["season"].agg(["min", "max", "count"])
               .reset_index().sort_values(["era_city", "era_name"]))
    rows = [[c + " " + n, str(lo) + "-" + str(hi), str(k), str(lo) + "-" + slug]
            for c, n, lo, hi, k, slug in zip(by_name["era_city"], by_name["era_name"], by_name["min"],
                                              by_name["max"], by_name["count"],
                                              by_name["era_name"].str.lower().str.replace(" ", "-"))]
    return "\n\n".join([
        str(len(old)) + " team-seasons from " + str(FIRST_SEASON) + " to " + str(LAST_OLDER_SEASON)
        + "; " + str(len(ident)) + " from " + str(FIRST_SEASON) + " to 2026, every key unique. "
        "Keys for seasons the export already serves are unchanged (names still come from "
        "TeamStatisticsExtended.csv wherever it has the season).",
        md_table(["Era-correct name", "Seasons", "Team-seasons", "First key"], rows),
    ])


# ---------------------------------------------------------------------------
# 3. Backtest
# ---------------------------------------------------------------------------

def build_older_matchups(allowed_ids: set) -> pd.DataFrame:
    games = load_games(FIRST_SEASON, allowed_ids)
    games = games[games["season"] <= LAST_OLDER_SEASON]
    stats = load_team_games(FIRST_SEASON, allowed_ids)
    stats = stats[stats["season"] <= LAST_OLDER_SEASON]
    out = attach_point_in_time_profiles(games, stats)
    out = out.sort_values(["season", "game_date"]).reset_index(drop=True)
    if out.empty or out["game_id"].duplicated().any():
        raise ValueError("Older-season matchup rows are empty or have duplicate game_ids.")
    return out


def build_formula_1997(allowed_ids: set) -> pd.DataFrame:
    """1996-97 games rebuilt with box-score formulas instead of the NBA's values."""
    games = load_games(LAST_OLDER_SEASON, allowed_ids)
    games = games[games["season"] == LAST_OLDER_SEASON]
    basic = _read_team_games(BASIC_STATS_PATH)
    basic = basic[basic["season"] == LAST_OLDER_SEASON]
    basic = compute_box_score_advanced(basic)
    basic[UNMATCHED_FORMULA_COLS] = np.nan     # as load_team_games treats older seasons
    basic = basic[basic["teamId"].isin(allowed_ids)]
    return attach_point_in_time_profiles(games, basic)


def score(df: pd.DataFrame, release) -> pd.DataFrame:
    """Home-win probability from the release, built the way predict_matchup builds its row."""
    data = {}
    for col in release.columns:
        if col.startswith("home_") or col.startswith("away_"):
            data[col] = df[col].to_numpy(dtype=float)
        elif col.endswith("_diff"):
            base = col[:-5]
            data[col] = df["home_" + base].to_numpy(dtype=float) - df["away_" + base].to_numpy(dtype=float)
        else:
            raise ValueError("Unrecognized model column: " + col)
    X = pd.DataFrame(data, columns=release.columns)
    classes = list(release.classifier.classes_)
    out = df[["game_id", "season", "game_type", "home_win", "home_team_id", "away_team_id",
              "home_regular_games_played", "away_regular_games_played",
              "home_regular_win_pct", "away_regular_win_pct"]].copy()
    out["p_home"] = release.classifier.predict_proba(X)[:, classes.index(1)]
    return out


def metrics(s: pd.DataFrame) -> dict:
    y, p = s["home_win"].to_numpy(), np.clip(s["p_home"].to_numpy(), 1e-15, 1 - 1e-15)
    better = np.where(s["home_regular_win_pct"] >= s["away_regular_win_pct"], 1, 0)
    return {
        "n":        len(s),
        "accuracy": float(((p >= 0.5).astype(int) == y).mean()),
        "log_loss": float(-(y * np.log(p) + (1 - y) * np.log(1 - p)).mean()),
        "brier":    float(((p - y) ** 2).mean()),
        "home":     float(y.mean()),
        "better":   float((better == y).mean()),
    }


def metric_row(label: str, s: pd.DataFrame) -> list:
    if s.empty:
        return [label, "0", "", "", "", "", ""]
    m = metrics(s)
    return [label, f"{m['n']:,}", fmt(m["accuracy"] * 100, 1) + "%", fmt(m["log_loss"], 4), fmt(m["brier"], 4),
            fmt(m["home"] * 100, 1) + "%", fmt(m["better"] * 100, 1) + "%"]


METRIC_HEADERS = ["Games", "n", "Accuracy", "Log loss", "Brier", "Home team wins", "Better record wins"]


def calibration_table(s: pd.DataFrame) -> list:
    bins = pd.cut(s["p_home"], CALIBRATION_BINS, include_lowest=True)
    rows = []
    for interval, g in s.groupby(bins, observed=True):
        rows.append([f"{max(interval.left, 0):.1f}-{interval.right:.1f}", f"{len(g):,}",
                     fmt(g["p_home"].mean() * 100, 1) + "%", fmt(g["home_win"].mean() * 100, 1) + "%"])
    return rows


def backtest_section(scored: pd.DataFrame, formula_1997: pd.DataFrame, nba_1997: pd.DataFrame,
                     release, dropped: dict) -> tuple[str, dict]:
    summary_rows, type_rows = [], []
    for label, lo, hi in PERIODS:
        p = scored[(scored["season"] >= lo) & (scored["season"] <= hi)]
        summary_rows.append(metric_row(label, p))
        for gt in (GAME_TYPE_REGULAR, GAME_TYPE_PLAYOFF):
            type_rows.append(metric_row(label + ", " + gt.lower(), p[p["game_type"] == gt]))
        reg = p[p["game_type"] == GAME_TYPE_REGULAR]
        settled = reg[(reg["home_regular_games_played"] >= 20) & (reg["away_regular_games_played"] >= 20)]
        type_rows.append(metric_row(label + ", regular season after 20 games", settled))

    season_rows = []
    for season, g in scored.groupby("season"):
        r = metric_row(str(season), g)
        r.insert(2, f"{int((g['game_type'] == GAME_TYPE_PLAYOFF).sum()):,}")
        season_rows.append(r)

    older = scored[scored["season"] <= LAST_OLDER_SEASON]
    test  = scored[scored["season"] >= 2022]
    calib = []
    for label, s in (("1986-1997", older), ("2022-2026 (test)", test),
                     ("1986-1997 playoffs", older[older["game_type"] == GAME_TYPE_PLAYOFF]),
                     ("2022-2026 playoffs", test[test["game_type"] == GAME_TYPE_PLAYOFF])):
        calib.append("**" + label + "**\n\n" + md_table(["Predicted home win", "Games", "Mean predicted", "Home won"],
                                                         calibration_table(s)))

    # 1996-97 twice: NBA values vs box-score formulas
    both = nba_1997.merge(formula_1997[["game_id", "p_home"]], on="game_id", suffixes=("", "_formula"))
    delta = (both["p_home_formula"] - both["p_home"]).abs()
    flips = int(((both["p_home"] >= 0.5) != (both["p_home_formula"] >= 0.5)).sum())
    f97 = both.drop(columns="p_home").rename(columns={"p_home_formula": "p_home"})

    key = {
        "older":    metrics(older),
        "older_po": metrics(older[older["game_type"] == GAME_TYPE_PLAYOFF]),
        "test":     metrics(test),
        "test_po":  metrics(test[test["game_type"] == GAME_TYPE_PLAYOFF]),
        "val":      metrics(scored[(scored["season"] >= 2019) & (scored["season"] <= 2021)]),
        "delta_mean": float(delta.mean()), "delta_max": float(delta.max()), "flips": flips, "n97": len(both),
    }

    text = "\n\n".join([
        "Release scored: `" + release.version + "` (" + str(len(release.columns)) + " columns, trained on "
        "playoff games through " + str(release.manifest.get("trainedThroughSeason")) + "). Each game is scored "
        "with the real home and away sides, from point-in-time profiles: only games that tipped off "
        "earlier that season, ordered by `gameDateTimeEst`, exactly as `build_matchup_training_data.py` "
        "builds them. A game is scored when both teams have played at least one regular-season game "
        "that season (" + f"{dropped['older']:,}" + " opening games dropped in 1986-1997, "
        + f"{dropped['modern']:,}" + " from 1998 on). \"Better record wins\" picks the team with the "
        "higher season-to-date win percentage (home team on a tie); it is a baseline, not the model.",
        "The 1998-2018 rows are the seasons `hist-v1` trained on, with leaky features at the time, so "
        "they flatter it and are shown only for reference. The honest comparison for 1986-1997 is "
        "the validation and test seasons.",
        "### Summary\n\n" + md_table(METRIC_HEADERS, summary_rows),
        "### Regular season and playoffs\n\n" + md_table(METRIC_HEADERS, type_rows),
        "### By season\n\n" + md_table(["Season", "n", "Playoff games"] + METRIC_HEADERS[2:], season_rows),
        "### Calibration\n\n" + "\n\n".join(calib),
        "### 1996-97 with the NBA's values versus the box-score formulas\n\n"
        "1996-97 is the one season that is both out of sample and covered by the NBA's own advanced "
        "values, so it shows what the formulas alone do to the model's output. Same "
        + f"{len(both):,}" + " games, same model, profiles built from each source (rebound percentages "
        "left blank in the formula version, as they are for older seasons).\n\n"
        + md_table(METRIC_HEADERS, [metric_row("1996-97, NBA values", nba_1997.merge(both[["game_id"]], on="game_id")),
                                    metric_row("1996-97, box-score formulas", f97)])
        + "\n\nMean absolute change in the home-win probability: " + fmt(delta.mean() * 100, 2)
        + " points (max " + fmt(delta.max() * 100, 2) + "). Picks that flip: " + str(flips) + " of "
        + f"{len(both):,}" + ".",
    ])
    return text, key


# ---------------------------------------------------------------------------
# 4. Era drift
# ---------------------------------------------------------------------------

def drift_section(stats: pd.DataFrame) -> str:
    reg = stats[stats["gameType"] == GAME_TYPE_REGULAR].copy()
    reg["three_rate"] = reg["threePointersAttempted"] / reg["fieldGoalsAttempted"]
    league = reg.groupby("season")[[c for _l, c, _d in DRIFT_STATS]].mean()
    modern = league.loc[2022:2026].mean()
    rows = []
    for season, r in league.iterrows():
        source = "box score" if season <= EXTENDED_STATS_START else "NBA"
        rows.append([str(season)] + [fmt(r[c], d) for _l, c, d in DRIFT_STATS] + [source])
    rows.append(["2022-2026 mean"] + [fmt(modern[c], d) for _l, c, d in DRIFT_STATS] + [""])
    return "\n\n".join([
        "League average per team-game, regular season. Ratings, pace and TS% for seasons before "
        "1996-97 come from the box-score formulas; from 1996-97 on they are the NBA's values. "
        "3PA rate is three-point attempts / field-goal attempts.",
        md_table(["Season"] + [l for l, _c, _d in DRIFT_STATS] + ["Source"], rows),
    ])


def season_label_checks(stats: pd.DataFrame) -> str:
    t = pd.to_datetime(stats["gameDateTimeEst"], format="mixed")
    older = stats[stats["season"] <= LAST_OLDER_SEASON]
    older_t = t[older.index]
    october_end = int(((older_t.dt.month == 10) & (older_t.dt.year == older["season"])).sum())
    bubble = stats[(t >= "2020-10-01") & (t < "2020-10-15") & (stats["gameType"] == GAME_TYPE_PLAYOFF)]
    return ("- Games from 1986-1997 played in October of the year their season ends: "
            + str(october_end) + ". Every older season starts in late October or November and ends by June.\n"
            "- 2020 playoff games played in October 2020 (the bubble Finals): " + str(bubble["gameId"].nunique()) + " games, labelled season "
            + ", ".join(str(s) for s in sorted(bubble["season"].unique())) + " by the `month < 10` rule. "
            "This is existing behaviour for every script, not new in F11; it moves those games into "
            "2020-21's playoff profiles, so 2020 and 2021 per-season figures should be read with that in mind.")


# ---------------------------------------------------------------------------
# 5. Era probe
# ---------------------------------------------------------------------------

def to_relative(values: pd.DataFrame, ref_seasons: pd.Series, ref: pd.DataFrame) -> pd.DataFrame:
    """Each PROBE_STATS column as a z-score against the league in ref_seasons."""
    out = values.copy()
    for stat in PROBE_STATS:
        mean = ref_seasons.map(ref[(stat, "mean")])
        std  = ref_seasons.map(ref[(stat, "std")]).where(lambda x: x > 0)
        out[stat] = (values[stat] - mean) / std
    return out


def probe_game_matrix(games: pd.DataFrame, ref=None) -> pd.DataFrame:
    """home_/away_/_diff probe features for real games; relative to the PREVIOUS season when ref is given."""
    sides = {}
    for side in ("home", "away"):
        v = games[[side + "_" + s for s in PROBE_STATS]].set_axis(PROBE_STATS, axis=1)
        sides[side] = to_relative(v, games["season"] - 1, ref) if ref is not None else v
    data = {}
    for stat in PROBE_STATS:
        data["home_" + stat] = sides["home"][stat].to_numpy()
        data["away_" + stat] = sides["away"][stat].to_numpy()
        data[stat + "_diff"] = data["home_" + stat] - data["away_" + stat]
    return pd.DataFrame(data)


def neutral_pairs(model, cols: list, profiles: pd.DataFrame, older_idx: np.ndarray, modern_idx: np.ndarray) -> np.ndarray:
    """Neutral P(older team wins) for every older x modern pair, as the export neutralises."""
    from scripts.export_static_site_data import build_base_stat_arrays, build_feature_chunk
    from src.models.release import parse_base_stats
    arrays = build_base_stat_arrays(profiles, parse_base_stats(cols))
    ii, jj = np.meshgrid(older_idx, modern_idx, indexing="ij")
    ii, jj = ii.ravel(), jj.ravel()
    win = list(model.classes_).index(1)
    p_ab = model.predict_proba(build_feature_chunk(ii, jj, arrays, cols))[:, win]
    p_ba = model.predict_proba(build_feature_chunk(jj, ii, arrays, cols))[:, win]
    return (p_ab + (1 - p_ba)) / 2


def pair_summary(label: str, p: np.ndarray, matched: np.ndarray) -> list:
    return [label, fmt(p.mean() * 100, 1) + "%", fmt((p > 0.5).mean() * 100, 1) + "%",
            fmt(p[matched].mean() * 100, 1) + "%"]


def era_probe_section(profiles: pd.DataFrame, older: pd.DataFrame, modern: pd.DataFrame, release) -> tuple[str, dict]:
    ref = profiles.groupby("season")[PROBE_STATS].agg(["mean", "std"])
    y_col = "home_win"
    train = modern[(modern["season"] >= PROBE_TRAIN[0]) & (modern["season"] <= PROBE_TRAIN[1])]
    evals = [
        ("1987-1997", older[(older["season"] >= PROBE_OLDER_PAIRS[0]) & (older["season"] <= PROBE_OLDER_PAIRS[1])]),
        ("2019-2021", modern[(modern["season"] >= 2019) & (modern["season"] <= 2021)]),
        ("2022-2026", modern[modern["season"] >= 2022]),
        ("2024-2026", modern[modern["season"] >= 2024]),
    ]

    # Neutral pairings between completed seasons (full-season profiles)
    prof = profiles.reset_index(drop=True)
    older_idx  = prof.index[(prof["season"] >= PROBE_OLDER_PAIRS[0]) & (prof["season"] <= PROBE_OLDER_PAIRS[1])].to_numpy()
    modern_idx = prof.index[(prof["season"] >= PROBE_MODERN_PAIRS[0]) & (prof["season"] <= PROBE_MODERN_PAIRS[1])].to_numpy()
    net = prof["regular_net_rating"].to_numpy()
    matched = (np.abs(net[older_idx][:, None] - net[modern_idx][None, :]) < 1.0).ravel()

    game_rows, pair_rows, key = [], [], {}
    for label, use_ref in (("Raw inputs", None), ("League-relative inputs", ref)):
        model = Pipeline([("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler()),
                          ("clf", LogisticRegression(C=1.0, max_iter=3000))])
        model.fit(probe_game_matrix(train, use_ref), train[y_col])
        for eval_label, e in evals:
            p = model.predict_proba(probe_game_matrix(e, use_ref))[:, 1]
            scored = pd.DataFrame({"home_win": e[y_col].to_numpy(), "p_home": p,
                                   "home_regular_win_pct": e["home_regular_win_pct"].to_numpy(),
                                   "away_regular_win_pct": e["away_regular_win_pct"].to_numpy()})
            game_rows.append(metric_row(label + ", " + eval_label, scored)[:5])

        # A completed season is compared with its own league here (the served-profile
        # question Session 2 decides); training used the previous season.
        pair_prof = to_relative(prof, prof["season"], ref) if use_ref is not None else prof
        cols = list(probe_game_matrix(train.head(1)).columns)
        p = neutral_pairs(model, cols, pair_prof, older_idx, modern_idx)
        pair_rows.append(pair_summary("Probe, " + label.lower(), p, matched))
        key[label] = float(p[matched].mean())

    p = neutral_pairs(release.classifier, release.columns, prof, older_idx, modern_idx)
    pair_rows.insert(0, pair_summary("`" + release.version + "` (served)", p, matched))
    key[release.version] = float(p[matched].mean())

    text = "\n\n".join([
        "Two probe models, not releases: the same logistic regression on the same " + str(len(PROBE_STATS))
        + " regular-season stats (home, away and difference), trained on point-in-time games from "
        + str(PROBE_TRAIN[0]) + "-" + str(PROBE_TRAIN[1]) + ". \"Raw\" reads the stats as they are. "
        "\"League-relative\" reads each one as a z-score against the previous season's teams "
        "(the point-in-time rule; `_build_pool` in `train_model_experiments.py` does the same). "
        "1986 has no previous season, so these rows start in 1987. 2022 is almost missing from the "
        "profiles (2 team-seasons of 1 game each; see CONTRIBUTING.md), so 2023 is measured against "
        "a meaningless reference: the 2024-2026 rows show the relative probe without that defect.",
        "**Real games** (both teams always from the same season)\n\n"
        + md_table(["Model, seasons", "n", "Accuracy", "Log loss", "Brier"], game_rows),
        "**Cross-era pairings**: every " + str(PROBE_OLDER_PAIRS[0]) + "-" + str(PROBE_OLDER_PAIRS[1])
        + " team-season against every " + str(PROBE_MODERN_PAIRS[0]) + "-" + str(PROBE_MODERN_PAIRS[1])
        + " team-season (" + f"{len(older_idx) * len(modern_idx):,}" + " pairs), full-season profiles, "
        "neutral court as the export computes it. For the league-relative probe a completed season is "
        "measured against its own league. \"Matched quality\" keeps the " + f"{int(matched.sum()):,}"
        + " pairs whose season net ratings are within 1 point: a model with no era preference "
        "should give those about 50%.\n\n"
        + md_table(["Model", "Mean P(older team wins)", "Older team favoured", "Matched quality: mean P(older)"], pair_rows),
    ])
    return text, key


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def write_report(body: str) -> None:
    head = ("# Older seasons backtest (F11 Session 1)\n\n"
            "_Summary and recommendation to be written above the marker._\n\n")
    if REPORT_PATH.exists():
        existing = REPORT_PATH.read_text(encoding="utf-8")
        if REPORT_MARKER in existing:
            head = existing.split(REPORT_MARKER)[0]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(head + REPORT_MARKER + "\n\n" + body + "\n", encoding="utf-8")


def main():
    allowed_ids = load_allowed_team_ids()
    release = load_active_release()
    print("Release: " + release.version)

    print("Validating box-score formulas against the NBA's values...")
    formula_text, verdicts = validate_formulas(allowed_ids)

    print("Building " + str(FIRST_SEASON) + "-2026 season profiles...")
    stats    = load_team_games(FIRST_SEASON, allowed_ids)
    profiles = build_season_profiles(stats)
    identity_text = identity_section(profiles)

    print("Building point-in-time rows for " + str(FIRST_SEASON) + "-" + str(LAST_OLDER_SEASON) + "...")
    older = build_older_matchups(allowed_ids)
    OLDER_PATH.parent.mkdir(parents=True, exist_ok=True)
    older.to_csv(OLDER_PATH, index=False)
    print("Older-season matchup rows: " + str(len(older)) + "  -> " + str(OLDER_PATH))

    modern = pd.read_csv(MATCHUP_PATH, low_memory=False)
    if modern["season"].min() <= LAST_OLDER_SEASON:
        raise ValueError("matchup_training_data.csv already holds seasons up to " + str(LAST_OLDER_SEASON)
                         + "; this backtest expects them only in " + OLDER_PATH.name)

    def scoreable(df):
        return df[(df["home_regular_games_played"] >= 1) & (df["away_regular_games_played"] >= 1)]

    older_ok, modern_ok = scoreable(older), scoreable(modern)
    dropped = {"older": len(older) - len(older_ok), "modern": len(modern) - len(modern_ok)}
    scored = pd.concat([score(older_ok, release), score(modern_ok, release)], ignore_index=True)

    nba_1997     = scored[scored["season"] == LAST_OLDER_SEASON]
    formula_1997 = score(scoreable(build_formula_1997(allowed_ids)), release)
    backtest_text, key = backtest_section(scored, formula_1997, nba_1997, release, dropped)

    print("Running the era probe...")
    probe_text, probe_key = era_probe_section(profiles, scoreable(older), modern_ok, release)

    body = "\n\n".join([
        "## Formula validation\n\n" + formula_text,
        "## Identity\n\n" + identity_text,
        "## Backtest of `" + release.version + "`\n\n" + backtest_text,
        "## Era drift\n\n" + drift_section(stats),
        "## Era probe\n\n" + probe_text,
        "## Season labels\n\n" + season_label_checks(stats),
    ])
    write_report(body)

    unusable = [k for k, ok in verdicts.items() if not ok]
    print("Formulas not usable: " + (", ".join(unusable) if unusable else "none"))
    for name in ("older", "older_po", "val", "test", "test_po"):
        m = key[name]
        print(f"  {name:9s} n={m['n']:6d}  acc={m['accuracy']:.4f}  logloss={m['log_loss']:.4f}  brier={m['brier']:.4f}")
    print(f"  1997 NBA vs formula: mean |dp|={key['delta_mean']:.4f}  max={key['delta_max']:.4f}  flips={key['flips']}/{key['n97']}")
    for name, p in probe_key.items():
        print(f"  matched-quality P(older wins), {name}: {p:.4f}")
    print("Report written to: " + str(REPORT_PATH))


if __name__ == "__main__":
    main()
