"""
evaluate_hist_v2.py

F11 Phase A: the evidence the owner decides hist-v2 on. Scores hist-v2 and
hist-v1 on the same point-in-time games (historical_training_data.csv), and
compares what each would serve, into reports/hist_v2_evaluation.md.

1. Data fixes. Blank game types per season (and what they were), and which
   served team-seasons the 2021-22 / 2000-01 fill and the October 2020 Finals
   rule change.
2. Real games. Accuracy, log loss, Brier and ROC-AUC on validation (2019-21)
   and test (2022-26), by game type, with "home team wins" and "better record
   wins" baselines; by season 1987-2026; calibration on the test seasons.
3. Cross-era check. Every 1987-97 team-season against every 2022-26 one,
   neutral court as the export computes it. Matched-quality pairs (season net
   ratings within 1 point) should come out near 50%.
4. Before and after. Neutral P(team A wins): hist-v1 as served today
   (frontend/public/data/teams/) against hist-v2 on the Phase B profiles
   (1986-2026, own-season z-scores), for named pairs and the Champions Bracket.
5. Top and bottom team-seasons by mean neutral win probability, the margin
   regressor's error, and the columns hist-v2 reads with their weights.

Only the section below REPORT_MARKER is regenerated; the summary above it is
written by hand and kept.

Run from repo root (after build_historical_training_data.py, training, and
promote_release.py --build hist-v2):
    python scripts/evaluate_hist_v2.py
"""

import json
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, roc_auc_score

REPO_ROOT = Path(__file__).resolve().parent.parent
for _p in (REPO_ROOT, REPO_ROOT / "backend" / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from build_team_season_profiles_extended import (
    BASIC_STATS_PATH,
    GAME_ID_PREFIX_TYPES,
    GAME_TYPE_PLAYOFF,
    GAME_TYPE_REGULAR,
    GAMES_TABLE_PATH,
    MODERN_ERA_START,
    OLDER_ERA_START,
    STATS_PATH,
    add_own_season_relative_columns,
    build_season_profiles,
    game_id_prefix,
    load_allowed_team_ids,
    load_team_games,
)
from scripts.backtest_older_seasons import calibration_table, fmt, md_table, metrics, score
from scripts.export_static_site_data import attach_identity, score_all_ordered_pairs
from src.models.release import RELEASES_DIR, load_release

HISTORICAL_PATH = REPO_ROOT / "data" / "processed" / "historical_training_data.csv"
SERVED_DIR      = REPO_ROOT / "frontend" / "public" / "data"
CURATED_PATH    = REPO_ROOT / "frontend" / "src" / "data" / "curated-tournaments.ts"
HIST_V2_EXP_DIR = REPO_ROOT / "models" / "experiments" / "hist_v2"
REPORT_PATH     = REPO_ROOT / "reports" / "hist_v2_evaluation.md"

REPORT_MARKER = "<!-- Everything below is generated by scripts/evaluate_hist_v2.py -->"

NEW, OLD = "hist-v2", "hist-v1"
SETTLED_GAMES = 20
OLDER_PAIRS   = (1987, MODERN_ERA_START)
MODERN_PAIRS  = (2022, 2026)

PERIODS = [
    ("Validation, 2019-2021", 2019, 2021),
    ("Test, 2022-2026",       2022, 2026),
]

NAMED_PAIRS = [
    ("1998-bulls",   "2017-warriors"),
    ("1998-jazz",    "2016-cavaliers"),
    ("1996-bulls",   "2017-warriors"),
    ("1986-celtics", "2008-celtics"),
    ("1989-pistons", "2004-pistons"),
    ("1987-lakers",  "2001-lakers"),
    ("1992-bulls",   "1996-bulls"),
    ("1995-rockets", "2022-warriors"),
]


# ---------------------------------------------------------------------------
# Scoring helpers
# ---------------------------------------------------------------------------

def full_metrics(s: pd.DataFrame) -> dict:
    m = metrics(s)
    y = s["home_win"].to_numpy()
    m["roc_auc"] = float(roc_auc_score(y, s["p_home"])) if len(np.unique(y)) == 2 else np.nan
    return m


def pct(x) -> str:
    return fmt(x * 100, 1) + "%"


def settled(df: pd.DataFrame) -> pd.Series:
    return (df["home_regular_games_played"] >= SETTLED_GAMES) & (df["away_regular_games_played"] >= SETTLED_GAMES)


def neutral_matrix(profiles: pd.DataFrame, release) -> tuple[np.ndarray, np.ndarray]:
    """Neutral P(row team beats column team) and margin, exactly as the export rounds them."""
    P, M = score_all_ordered_pairs(profiles, release.classifier, release.regressor, release.columns)
    N  = np.round((P + (1 - P.T)) / 2, 4)
    NM = np.round((M - M.T) / 2, 1)
    np.fill_diagonal(N, np.nan)
    np.fill_diagonal(NM, np.nan)
    return N, NM


def pair_probability(profiles: pd.DataFrame, release, key_a: str, key_b: str) -> float:
    pair = profiles[profiles["key"].isin([key_a, key_b])].set_index("key").loc[[key_a, key_b]].reset_index()
    P, _M = score_all_ordered_pairs(pair, release.classifier, release.regressor, release.columns)
    return round(float((P[0, 1] + (1 - P[1, 0])) / 2), 4)


def served_probability(key_a: str, key_b: str):
    path = SERVED_DIR / "teams" / (key_a + ".json")
    if not path.exists():
        return None
    return json.loads(path.read_text())["opponents"].get(key_b, {}).get("p")


def curated_entrants() -> list:
    text = CURATED_PATH.read_text(encoding="utf-8")
    block = text[text.index("entrants:"):]
    block = block[:block.index("]")]
    return re.findall(r'"(\d{4}-[a-z0-9-]+)"', block)


# ---------------------------------------------------------------------------
# 1. Data fixes
# ---------------------------------------------------------------------------

def data_fixes_section(old_profiles: pd.DataFrame, new_profiles: pd.DataFrame) -> str:
    games = pd.read_csv(GAMES_TABLE_PATH, usecols=["gameId", "gameType"], low_memory=False).drop_duplicates("gameId")
    rows = []
    for path in (STATS_PATH, BASIC_STATS_PATH):
        s = pd.read_csv(path, usecols=["gameId", "gameDateTimeEst", "gameType"], low_memory=False)
        t = pd.to_datetime(s["gameDateTimeEst"], format="mixed")
        s["season"] = t.dt.year.where(t.dt.month < 10, t.dt.year + 1)
        blank = s[s["gameType"].isna()].merge(games.rename(columns={"gameType": "games_csv"}), on="gameId", how="left")
        blank["counted"] = game_id_prefix(blank["gameId"]).isin(GAME_ID_PREFIX_TYPES)
        for season, g in blank.groupby("season"):
            kinds = g["games_csv"].fillna("none").value_counts()
            rows.append([path.name, str(season), f"{len(g):,}", f"{int(g['counted'].sum()):,}",
                         ", ".join(k + " " + f"{v:,}" for k, v in kinds.items())])

    # Which served (1998 on) team-seasons change
    key = ["team_id", "season"]
    old = old_profiles.set_index(key)
    new = new_profiles[new_profiles["season"] > MODERN_ERA_START].set_index(key)
    added = new.index.difference(old.index)
    both  = new.index.intersection(old.index)
    num = [c for c in old.columns if c in new.columns and pd.api.types.is_numeric_dtype(old[c])]
    a, b = old.loc[both, num], new.loc[both, num]
    changed = ((a - b).abs() > 1e-9) | (a.isna() != b.isna())
    reg_changed = changed[[c for c in num if c.startswith("regular_")]].any(axis=1)
    po_changed  = changed[[c for c in num if c.startswith("playoff_")]].any(axis=1)
    change_rows = []
    for idx in both[reg_changed | po_changed]:
        n = new.loc[idx]
        o = old.loc[idx]
        what = []
        if reg_changed.loc[idx]:
            what.append("regular season " + str(int(o["regular_games_played"])) + " -> " + str(int(n["regular_games_played"])) + " games")
        if po_changed.loc[idx]:
            what.append("playoffs " + str(int(o["playoff_games_played"])) + " -> " + str(int(n["playoff_games_played"])) + " games")
        change_rows.append([str(idx[1]), n["team_city"] + " " + n["team_name"], "; ".join(what)])
    by_season = pd.Series([r[0] for r in change_rows]).value_counts().sort_index()

    finals = [r for r in change_rows if r[0] in ("2020", "2021")]
    return "\n\n".join([
        "### Blank `gameType` rows in the raw team-game files\n\n"
        "Every script drops a row whose `gameType` is blank. `Games.csv` has a type for every game. "
        "hist-v2 fills a blank only for a counted type (game id prefix 2 regular season, 4 playoffs, "
        "5 play-in) and raises if one stays blank or disagrees with its id; preseason (prefix 1) and "
        "NBA Cup (prefix 6) rows stay out.",
        md_table(["File", "Season", "Blank rows", "Counted (filled)", "Type in Games.csv"], rows),
        "### Served team-seasons that change (Phase B)\n\n"
        + f"{len(added)}" + " team-seasons from 1998 on are added (all from 2022: "
        + ", ".join(sorted(str(s) for s in new.loc[added].reset_index()["season"].unique())) + "). "
        + f"{len(change_rows)}" + " already-served team-seasons get different stats: "
        + ", ".join(f"{s}: {n}" for s, n in by_season.items()) + ". "
        "The 2001 and 2022 rows gain the regular-season games their blank game types hid; "
        "2022's two served one-game teams (`2022-clippers` 1-0, `2022-lakers` 0-1) get full seasons. "
        "The October 2020 Finals move from 2021 to 2020:",
        md_table(["Season", "Team", "Change"], finals),
    ])


# ---------------------------------------------------------------------------
# 2. Real games
# ---------------------------------------------------------------------------

def real_games_section(rows: pd.DataFrame, scored: dict) -> tuple[str, dict]:
    headers = ["Games", "Model", "n", "Accuracy", "Log loss", "Brier", "ROC-AUC", "Home team wins", "Better record wins"]
    table, key = [], {}
    for label, lo, hi in PERIODS:
        for part, mask_fn in (("all", lambda d: d["season"] > 0),
                              ("both teams 20+ games", settled),
                              ("regular season", lambda d: d["game_type"] == GAME_TYPE_REGULAR),
                              ("playoffs", lambda d: d["game_type"] == GAME_TYPE_PLAYOFF)):
            for model in (NEW, OLD):
                s = scored[model]
                s = s[(s["season"] >= lo) & (s["season"] <= hi)]
                s = s[mask_fn(s)]
                m = full_metrics(s)
                key[(label, part, model)] = m
                table.append([label + ", " + part, "`" + model + "`", f"{m['n']:,}", pct(m["accuracy"]),
                              fmt(m["log_loss"], 4), fmt(m["brier"], 4), fmt(m["roc_auc"], 3),
                              pct(m["home"]), pct(m["better"])])

    season_rows = []
    for season in sorted(rows["season"].unique()):
        n = scored[NEW][scored[NEW]["season"] == season]
        o = scored[OLD][scored[OLD]["season"] == season]
        mn, mo = metrics(n), metrics(o)
        season_rows.append([str(season), f"{mn['n']:,}", f"{int((n['game_type'] == GAME_TYPE_PLAYOFF).sum()):,}",
                            pct(mn["accuracy"]), fmt(mn["log_loss"], 4), pct(mo["accuracy"]), fmt(mo["log_loss"], 4),
                            pct(mn["better"])])

    calib = []
    for model in (NEW, OLD):
        t = scored[model][scored[model]["season"] >= 2022]
        calib.append("**`" + model + "`, test seasons 2022-2026**\n\n"
                     + md_table(["Predicted home win", "Games", "Mean predicted", "Home won"], calibration_table(t)))
        po = t[t["game_type"] == GAME_TYPE_PLAYOFF]
        calib.append("**`" + model + "`, test-season playoffs**\n\n"
                     + md_table(["Predicted home win", "Games", "Mean predicted", "Home won"], calibration_table(po)))

    text = "\n\n".join([
        "Both releases score the same rows: every game in `historical_training_data.csv` (point-in-time "
        "profiles, playoff games in the calendar year they were played, 2001 and 2022 game types filled) "
        "in which both teams had played at least one regular-season game. Each game is scored with its real "
        "home and away sides. `hist-v1` reads the raw stats; `hist-v2` reads them as z-scores against the "
        "previous season. \"Better record wins\" picks the higher season-to-date win percentage (home on a "
        "tie). `hist-v2` was chosen on the \"both teams 20+ games\" validation rows; test was scored once.",
        md_table(headers, table),
        "### By season\n\n" + md_table(["Season", "n", "Playoff games", "hist-v2 accuracy", "hist-v2 log loss",
                                         "hist-v1 accuracy", "hist-v1 log loss", "Better record wins"], season_rows),
        "### Calibration\n\n" + "\n\n".join(calib),
    ])
    return text, key


# ---------------------------------------------------------------------------
# 3-5. Served profiles: cross-era, before/after, rankings
# ---------------------------------------------------------------------------

def cross_era_section(profiles: pd.DataFrame, N: dict) -> tuple[str, dict]:
    older  = profiles.index[(profiles["season"] >= OLDER_PAIRS[0]) & (profiles["season"] <= OLDER_PAIRS[1])].to_numpy()
    modern = profiles.index[(profiles["season"] >= MODERN_PAIRS[0]) & (profiles["season"] <= MODERN_PAIRS[1])].to_numpy()
    net = profiles["regular_net_rating"].to_numpy()
    matched = np.abs(net[older][:, None] - net[modern][None, :]) < 1.0
    rows, key = [], {}
    for model in (NEW, OLD):
        p = N[model][np.ix_(older, modern)]
        key[model] = float(p[matched].mean())
        rows.append(["`" + model + "`", pct(p.mean()), pct((p > 0.5).mean()), pct(p[matched].mean()),
                     fmt(np.abs(p[matched] - 0.5).mean() * 100, 1) + " pts"])
    text = ("Every " + str(OLDER_PAIRS[0]) + "-" + str(OLDER_PAIRS[1]) + " team-season against every "
            + str(MODERN_PAIRS[0]) + "-" + str(MODERN_PAIRS[1]) + " team-season (" + f"{matched.size:,}"
            + " pairs), on the Phase B profiles (1986-2026, full seasons), neutral court exactly as the export "
            "computes it. `hist-v2` measures each season against its own league; `hist-v1` reads raw stats. "
            "\"Matched quality\" keeps the " + f"{int(matched.sum()):,}" + " pairs whose season net ratings are "
            "within 1 point: a model with no era preference gives those about 50% on average.\n\n"
            + md_table(["Model", "Mean P(older team wins)", "Older team favoured", "Matched quality: mean P(older)",
                        "Matched quality: mean distance from 50%"], rows))
    return text, key


def before_after_section(profiles: pd.DataFrame, N: dict, NM: dict) -> tuple[str, list]:
    idx = {k: i for i, k in enumerate(profiles["key"])}

    def row(a, b):
        served = served_probability(a, b)
        v1 = N[OLD][idx[a], idx[b]]
        v2 = N[NEW][idx[a], idx[b]]
        return ["`" + a + "` vs `" + b + "`",
                pct(served) if served is not None else "not served",
                pct(v1), pct(v2), fmt(NM[NEW][idx[a], idx[b]], 1)]

    headers = ["Pair", "hist-v1 served today", "hist-v1 on Phase B profiles", "hist-v2", "hist-v2 margin (pts)"]
    named = [row(a, b) for a, b in NAMED_PAIRS]

    entrants = curated_entrants()
    ent_idx = [idx[k] for k in entrants]
    bracket = []
    for model in (OLD, NEW):
        sub = N[model][np.ix_(ent_idx, ent_idx)]
        mean = np.nanmean(sub, axis=1)
        order = (-mean).argsort().argsort() + 1
        bracket.append((mean, order))
    served_mean = []
    for a in entrants:
        ps = [served_probability(a, b) for b in entrants if b != a]
        served_mean.append(np.mean(ps) if all(p is not None for p in ps) else np.nan)
    ent_rows = [[str(i + 1), "`" + k + "`", pct(served_mean[i]), pct(bracket[1][0][i]), str(bracket[1][1][i]),
                 str((-np.array(served_mean)).argsort().argsort()[i] + 1)]
                for i, k in enumerate(entrants)]

    text = "\n\n".join([
        "Neutral-court P(first team wins). \"hist-v1 served today\" is the live site's number "
        "(`frontend/public/data/teams/`, current profiles). \"hist-v1 on Phase B profiles\" is what a "
        "rollback to `hist-v1` would serve after Phase B (1986 on, 2001 and 2022 fixed). The site shows the "
        "1998 Bulls vs 2017 Warriors as 73.8% for the Warriors: 0.2625 for the Bulls below (shown rounded).",
        md_table(headers, named),
        "### Champions Bracket entrants\n\n"
        "The 16 entrants of `champions-v1` (`frontend/src/data/curated-tournaments.ts`), in seed order. "
        "Mean neutral P(win) against the other 15, and the rank that gives inside the bracket.",
        md_table(["Seed", "Entrant", "hist-v1 served: mean P(win)", "hist-v2: mean P(win)", "hist-v2 rank",
                  "hist-v1 rank"], ent_rows),
    ])
    return text, named


def ranking_section(profiles: pd.DataFrame, N: dict) -> str:
    out = []
    for model in (NEW,):
        mean = np.nanmean(N[model], axis=1)
        order = np.argsort(-mean)
        def rows(ix):
            return [[str(r + 1) if r < 10 else str(len(order) - (len(order) - 1 - r)),
                     "`" + profiles.loc[i, "key"] + "`",
                     str(int(profiles.loc[i, "regular_wins"])) + "-" + str(int(profiles.loc[i, "regular_losses"])),
                     fmt(profiles.loc[i, "regular_net_rating"], 1), pct(mean[i])]
                    for r, i in ix]
        top    = rows([(r, order[r]) for r in range(10)])
        bottom = rows([(r, order[r]) for r in range(len(order) - 10, len(order))])
        headers = ["Rank", "Team-season", "Record", "Net rating", "Mean neutral P(win)"]
        out.append("**Top 10, `" + model + "`**\n\n" + md_table(headers, top))
        out.append("**Bottom 10, `" + model + "`**\n\n" + md_table(headers, bottom))
    return ("Each of the " + f"{len(profiles):,}" + " Phase B team-seasons against every other one, neutral court; "
            "the mean of its win probabilities.\n\n" + "\n\n".join(out))


def model_section(release, rows: pd.DataFrame, old) -> str:
    exp = json.loads((HIST_V2_EXP_DIR / "experiment_metrics.json").read_text())
    reg = exp["regression_summary"]
    test = rows[(rows["season"] >= 2022) & settled(rows)]

    def mae(r):
        X = pd.DataFrame({c: (test[c] if not c.endswith("_diff") or c in test.columns
                              else test["home_" + c[:-5]] - test["away_" + c[:-5]]) for c in r.columns})
        return mean_absolute_error(test["homeScore"] - test["awayScore"], r.regressor.predict(X[r.columns]))

    coef = pd.read_csv(HIST_V2_EXP_DIR / "feature_coefficients.csv")
    coef_rows, share = [], ""
    if "coefficient" in coef.columns:
        total = coef["abs_coefficient"].sum()
        for _, r in coef.iterrows():
            coef_rows.append(["`" + r["feature"] + "`", fmt(r["coefficient"], 3), pct(r["abs_coefficient"] / total if total else 0)])
        top = coef.iloc[0]
        share = ("The largest weight is `" + top["feature"] + "`, " + pct(top["abs_coefficient"] / total)
                 + " of the total absolute weight; the top three hold "
                 + pct(coef["abs_coefficient"].head(3).sum() / total) + ". For comparison, `hist-v1` put 1.19 on "
                 "`playoff_win_pct_diff` and 0.15 or less on everything else.")

    results = pd.read_csv(HIST_V2_EXP_DIR / "experiment_results.csv")
    best_by = (results.sort_values("validation_log_loss").groupby(["dataset_filter", "feature_set"]).head(1)
               .sort_values("validation_log_loss").head(12))
    sel_rows = [[r["dataset_filter"], r["feature_set"], r["model_type"] + " " + r["hyperparameters"],
                 f"{int(r['train_rows']):,}", fmt(r["validation_log_loss"], 4), pct(r["validation_accuracy"])]
                for _, r in best_by.iterrows()]

    return "\n\n".join([
        "### Selection\n\n" + exp["selection"] + " " + str(exp["classification_result_count"])
        + " candidates: " + str(results["feature_set"].nunique()) + " era-safe feature sets x "
        + str(results["dataset_filter"].nunique()) + " training filters x "
        + str(len(results) // (results["feature_set"].nunique() * results["dataset_filter"].nunique()))
        + " models. Train seasons "
        + str(exp["split"]["train"][0]) + "-" + str(exp["split"]["train"][1]) + ". Best candidate per filter and "
        "feature set:\n\n"
        + md_table(["Training rows", "Feature set", "Model", "Train rows", "Validation log loss", "Validation accuracy"], sel_rows),
        "Chosen: **" + exp["best_model_name"] + "** " + json.dumps(exp["best_hyperparameters"]) + ", feature set `"
        + exp["best_feature_set"] + "`, trained on `" + exp["best_dataset_filter"] + "` rows ("
        + f"{exp['best_train_rows']:,}" + ").",
        "### Margin regressor\n\n" + md_table(
            ["Model", "Estimator", "Validation MAE", "Test MAE (both 20+ games)", "Test MAE (all test games)"],
            [["`hist-v2`", reg["best_model"], fmt(reg["best_metrics"]["validation"]["mae"], 2),
              fmt(reg["best_metrics"]["test"]["mae"], 2), fmt(reg["best_metrics"]["test_all_games"]["mae"], 2)],
             ["`hist-v1`", old.regressor_name, "", fmt(mae(old), 2), ""]]),
        "### Columns and weights\n\n`hist-v2` reads " + str(len(release.columns)) + " columns. " + share,
        md_table(["Column", "Coefficient (standardised)", "Share of total weight"], coef_rows)
        if coef_rows else "Coefficients unavailable for " + exp["best_model_name"] + ".",
    ])


def release_section(release) -> str:
    """A copy of what promote_release.py built from release_info.json."""
    m = release.manifest
    return "\n\n".join([
        "`models/releases/" + release.version + "/manifest.json` (built from "
        "`models/experiments/hist_v2/release_info.json`, not activated).",
        "**Description.** " + m["description"],
        "**Limitations**\n\n" + "\n".join("- " + l for l in m["limitations"]),
        "**Source.** " + m["source"],
        "**metrics.json**\n\n```json\n" + json.dumps(release.metrics, indent=2) + "\n```",
    ])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def write_report(body: str) -> None:
    head = "# hist-v2 evaluation (F11 Phase A)\n\n_Summary to be written above the marker._\n\n"
    if REPORT_PATH.exists():
        existing = REPORT_PATH.read_text(encoding="utf-8")
        if REPORT_MARKER in existing:
            head = existing.split(REPORT_MARKER)[0]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(head + REPORT_MARKER + "\n\n" + body + "\n", encoding="utf-8")


def main():
    new = load_release(RELEASES_DIR / NEW)
    old = load_release(RELEASES_DIR / OLD)
    print("Releases: " + new.version + " (" + str(len(new.columns)) + " columns), " + old.version)

    rows = pd.read_csv(HISTORICAL_PATH, low_memory=False)
    rows = rows[(rows["home_regular_games_played"] >= 1) & (rows["away_regular_games_played"] >= 1)].reset_index(drop=True)
    scored = {m.version: score(rows, m).assign(season=rows["season"].to_numpy()) for m in (new, old)}

    print("Building Phase B profiles (1986 on, game types filled)...")
    ids = load_allowed_team_ids()
    new_profiles = build_season_profiles(load_team_games(OLDER_ERA_START + 1, ids, fill_game_types=True))
    old_profiles = build_season_profiles(load_team_games(MODERN_ERA_START + 1, ids))
    served = attach_identity(add_own_season_relative_columns(new_profiles)).reset_index(drop=True)
    print("Phase B team-seasons: " + str(len(served)))

    print("Scoring every ordered pair with both releases...")
    N, NM = {}, {}
    for m in (new, old):
        N[m.version], NM[m.version] = neutral_matrix(served, m)

    fixes_text = data_fixes_section(old_profiles, new_profiles)
    games_text, key = real_games_section(rows, scored)
    cross_text, cross_key = cross_era_section(served, N)
    before_text, named = before_after_section(served, N, NM)
    body = "\n\n".join([
        "## Data fixes\n\n" + fixes_text,
        "## Real games\n\n" + games_text,
        "## Cross-era check\n\n" + cross_text,
        "## Before and after\n\n" + before_text,
        "## Top and bottom team-seasons\n\n" + ranking_section(served, N),
        "## The model\n\n" + model_section(new, rows, old),
        "## Release record\n\n" + release_section(new),
    ])
    write_report(body)

    for (label, part, model), m in key.items():
        if part in ("all", "both teams 20+ games"):
            print(f"  {label:22s} {part:22s} {model}: n={m['n']:6d} acc={m['accuracy']:.4f} "
                  f"ll={m['log_loss']:.4f} brier={m['brier']:.4f} auc={m['roc_auc']:.4f}")
    for model, p in cross_key.items():
        print(f"  matched-quality P(older wins), {model}: {p:.4f}")
    for r in named:
        print("  " + " | ".join(r))
    print("Report written to: " + str(REPORT_PATH))


if __name__ == "__main__":
    main()
