"""
audit_model_features.py

Reads model artifacts and team season profile source data.
Outputs a human-readable Markdown summary of model features.

Run from repo root:
    python src/models/audit_model_features.py
"""

import json
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]

COLUMNS_PATH      = REPO_ROOT / "models" / "experiments" / "best_experiment_columns.json"
COEF_PATH         = REPO_ROOT / "models" / "experiments" / "feature_coefficients.csv"
METRICS_PATH      = REPO_ROOT / "models" / "experiments" / "experiment_metrics.json"
PROFILES_PATH     = REPO_ROOT / "data" / "processed" / "team_season_profiles_extended.csv"
OUTPUT_PATH       = REPO_ROOT / "models" / "experiments" / "model_feature_summary.md"


def categorize(col: str) -> str:
    if col.endswith("_diff"):
        return "Difference (home - away)"
    if col.startswith("home_regular_"):
        return "Team A / Regular Season"
    if col.startswith("away_regular_"):
        return "Team B / Regular Season"
    if col.startswith("home_playoff_") or col in ("home_made_playoffs", "home_made_play_in"):
        return "Team A / Playoff Context"
    if col.startswith("away_playoff_") or col in ("away_made_playoffs", "away_made_play_in"):
        return "Team B / Playoff Context"
    if "_z_" in col or col.endswith("_z"):
        return "Era-Adjusted (z-score)"
    if "_pctile" in col:
        return "Era-Adjusted (percentile)"
    return "Other"


def can_build(col: str, profile_cols: set) -> str:
    """Determine if a model column can be derived from the profile source data."""
    if col.endswith("_diff"):
        base = col[:-5]
        h_ok = ("home_" + base) in profile_cols or base in profile_cols
        a_ok = ("away_" + base) in profile_cols or base in profile_cols
        return "yes (computed)" if (h_ok or a_ok) else "no"
    if col.startswith("home_"):
        src = col[5:]
        return "yes" if src in profile_cols else "no"
    if col.startswith("away_"):
        src = col[5:]
        return "yes" if src in profile_cols else "no"
    return "unknown"


def main():
    with open(COLUMNS_PATH) as f:
        model_cols = json.load(f)

    coef_df  = pd.read_csv(COEF_PATH)
    with open(METRICS_PATH) as f:
        metrics  = json.load(f)

    profiles_sample = pd.read_csv(PROFILES_PATH, nrows=1)
    profile_cols    = set(profiles_sample.columns)

    # Augment profile_cols with home_/away_ prefixed versions (matchup row keys)
    prefixed = set()
    for c in profile_cols:
        prefixed.add("home_" + c)
        prefixed.add("away_" + c)
    profile_cols |= prefixed

    total_cols   = len(model_cols)
    nonzero_coef = coef_df[coef_df["abs_coefficient"] > 0].sort_values("abs_coefficient", ascending=False)
    top_pos      = coef_df[coef_df["coefficient"] > 0].sort_values("coefficient", ascending=False).head(15)
    top_neg      = coef_df[coef_df["coefficient"] < 0].sort_values("coefficient").head(15)

    missing = [c for c in model_cols if can_build(c, profile_cols) == "no"]

    lines = []

    lines += [
        "# Model Feature Summary",
        "",
        "Generated by `src/models/audit_model_features.py`.",
        "",
        "## Experiment Overview",
        "",
        "| Field | Value |",
        "| ----- | ----- |",
        "| Best model | " + metrics.get("best_model_name", "?") + " |",
        "| Dataset filter | " + metrics.get("best_dataset_filter", "?") + " |",
        "| Feature set | " + metrics.get("best_feature_set", "?") + " |",
        "| Hyperparameters | " + str(metrics.get("best_hyperparameters", {})) + " |",
        "| Total model columns | " + str(total_cols) + " |",
        "| Non-zero coefficients (L1 sparsity) | " + str(len(nonzero_coef)) + " |",
        "",
    ]

    val_m  = metrics.get("best_validation_metrics", {})
    test_m = metrics.get("best_test_metrics", {})
    lines += [
        "## Performance vs Baseline",
        "",
        "| Metric | Baseline | This Model (Val) | This Model (Test) |",
        "| ------ | -------- | ---------------- | ----------------- |",
        "| Accuracy | ~0.68 | " + str(val_m.get("accuracy", "?")) + " | " + str(test_m.get("accuracy", "?")) + " |",
        "| ROC-AUC | 0.738 | " + str(val_m.get("roc_auc", "?")) + " | " + str(test_m.get("roc_auc", "?")) + " |",
        "| Log-loss | 0.597 | " + str(val_m.get("log_loss", "?")) + " | " + str(test_m.get("log_loss", "?")) + " |",
        "| Brier score | - | " + str(val_m.get("brier_score", "?")) + " | " + str(test_m.get("brier_score", "?")) + " |",
        "",
    ]

    lines += [
        "## All Model Columns (" + str(total_cols) + ")",
        "",
        "| Column | Category | Buildable from Profile? | Coefficient |",
        "| ------ | -------- | ----------------------- | ----------- |",
    ]
    coef_map = dict(zip(coef_df["feature"], coef_df["coefficient"])) if not coef_df.empty else {}
    for col in model_cols:
        cat    = categorize(col)
        build  = can_build(col, profile_cols)
        coef   = coef_map.get(col, 0.0)
        coef_s = str(round(coef, 6)) if coef != 0.0 else "0 (zeroed by L1)"
        lines.append("| `" + col + "` | " + cat + " | " + build + " | " + coef_s + " |")
    lines.append("")

    lines += [
        "## Features Grouped by Category",
        "",
    ]
    categories = {}
    for col in model_cols:
        cat = categorize(col)
        categories.setdefault(cat, []).append(col)

    for cat, cols in sorted(categories.items()):
        lines.append("### " + cat + " (" + str(len(cols)) + " columns)")
        lines.append("")
        for c in cols:
            coef = coef_map.get(c, 0.0)
            marker = " ← **active**" if coef != 0.0 else ""
            lines.append("- `" + c + "`" + marker)
        lines.append("")

    lines += [
        "## Top Positive Coefficients (helps Team A / home win)",
        "",
        "| Rank | Feature | Coefficient |",
        "| ---- | ------- | ----------- |",
    ]
    for i, row in enumerate(top_pos.itertuples(), 1):
        lines.append("| " + str(i) + " | `" + row.feature + "` | " + str(round(row.coefficient, 6)) + " |")
    lines.append("")

    lines += [
        "## Top Negative Coefficients (hurts Team A / home win)",
        "",
        "| Rank | Feature | Coefficient |",
        "| ---- | ------- | ----------- |",
    ]
    for i, row in enumerate(top_neg.itertuples(), 1):
        lines.append("| " + str(i) + " | `" + row.feature + "` | " + str(round(row.coefficient, 6)) + " |")
    lines.append("")

    lines += [
        "## Missing / Unresolvable Columns",
        "",
    ]
    if missing:
        lines.append("The following model columns cannot currently be built from `team_season_profiles_extended.csv`:")
        lines.append("")
        for c in missing:
            lines.append("- `" + c + "`")
    else:
        lines.append("All model columns can be built from `team_season_profiles_extended.csv`. No gaps detected.")
    lines.append("")

    reg = metrics.get("regression_summary", {})
    lines += [
        "## Point Margin Regression",
        "",
        "| Field | Value |",
        "| ----- | ----- |",
        "| Best regression model | " + reg.get("best_model", "?") + " |",
        "| Validation MAE | " + str(reg.get("best_validation_mae", "?")) + " points |",
    ]
    best_reg_m = reg.get("best_metrics", {})
    for split, key in [("Validation", "validation"), ("Test", "test")]:
        m = best_reg_m.get(key, {})
        lines.append("| " + split + " RMSE | " + str(m.get("rmse", "?")) + " points |")
        lines.append("| " + split + " R² | " + str(m.get("r2", "?")) + " |")
    lines.append("")

    lines += [
        "## Why the Best Model Improved",
        "",
        "The key improvement came from two changes working together:",
        "",
        "**1. Training on playoff games only (`playoffs_only` dataset filter)**",
        "",
        "The baseline was trained on all game types. Playoff games have fundamentally",
        "different dynamics than regular season games: teams are more evenly matched,",
        "home court matters differently, and teams have adapted to each other over a series.",
        "By training only on playoff games, the model learns the signal relevant to the",
        "kinds of competitive matchups the simulator is designed to replicate.",
        "",
        "**2. Adding playoff context features (`regular_plus_playoff_context` feature set)**",
        "",
        "Regular season stats alone describe a team's average performance across 82 games.",
        "Playoff win percentage and playoff ratings describe how that team performed when",
        "it mattered most, against the best competition. L1 regularization (C=0.1) then",
        "identified `playoff_win_pct_diff` as the dominant signal by a wide margin",
        "(coefficient 1.19 vs next-highest 0.14). In the historical simulator context,",
        "a team's completed playoff record is a strong proxy for their tier of greatness.",
        "",
        "**3. L1 sparsity found the real signal**",
        "",
        "Of 71 input features, only 8 received non-zero coefficients. The L1 penalty",
        "discarded correlated and redundant features (many regular-season stats are",
        "highly correlated with each other) and focused on the handful of features with",
        "genuine predictive power for playoff game outcomes.",
        "",
        "**Practical implication for the simulator:**",
        "",
        "When comparing cross-era teams like 1998 Bulls vs 2017 Warriors, the model",
        "weights their completed playoff performance heavily. A team that went 15-2 in",
        "the playoffs will be predicted to beat a team that went 8-8, holding regular",
        "season stats roughly equal. This matches basketball intuition about dynasty teams.",
        "",
    ]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Feature summary written to: " + str(OUTPUT_PATH))
    print("Total model columns:        " + str(total_cols))
    print("Non-zero coefficients:      " + str(len(nonzero_coef)))
    print("Missing profile columns:    " + str(len(missing)))


if __name__ == "__main__":
    main()
